config/routes.rb
Rails.application.routes.draw do

  resources :conversations_users
  resources :conversations
  resources :geocoded_addresses
  resources :distances
  resources :request_accesses
  resources :flags
  resources :ratings

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get 'search/new_search'
  get 'search/index'
  get 'search/classic'

  match "/classic_driver", to: 'search#classic_driver', via: 'get'
  match "/people_data", to: 'search#people_data', via: 'get'
  match "/accessibility", to: 'static#accessibility', via: 'get'

  match "/newConversation/:other_participant_id", to: 'conversations#create', via: 'get'

  match '/people', to: 'search#people', via: 'get'
  match '/search', to: 'search#classic', via: 'get'
  match '/browse', to: 'search#new_search', via: 'get'

  resources :saveds
  resources :user_uploads
  resources :resource_uploads
  resources :resources_tags
  resources :newsletters

  match 'submit_resource', to: 'static#submit_resource', via: 'post'
  match '/resources/new', to: 'resources#new', via: 'get'
  match '/resources/clarifyContent', to: 'resources#clarifyContent', via: 'get'
  match '/resources/:id', to: 'resources#rerouter', via: 'get'

  resources :resources do
    get :autocomplete_tag_name, :on => :collection
  end

  match '/r/:id/:resource_name', to: 'resources#show', via: 'get'
  resources :resources
  match '/resources/:id/categories', to: 'resources#categories', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#weblinks', via: 'get'
  match '/resources/:id/photo', to: 'resources#photo', via: 'get'
  match '/resources/:id/success', to: 'resources#success', via: 'get'
  match '/resource_uploads/:id/crop', to: 'resource_uploads#crop', via: 'get'
  match '/user_uploads/:id/crop', to: 'user_uploads#crop', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#update_weblinks', via: 'post'

  match '/resources_tags/:resource_id/:tag_id/create', to: 'resources_tags#custom_create', via: 'post'
  match '/resources_tags/:resource_id/:tag_id/destroy', to: 'resources_tags#custom_destroy', via: 'post'

  match '/saved/:resource_id/:user_id/create', to: 'saveds#custom_create', via: 'post'
  match '/saved/:resource_id/:user_id/destroy', to: 'saveds#custom_destroy', via: 'post'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/users/:id/conversations' => 'users#conversations', via: 'get'
  match '/users/:id/conversations/:conversation_id' => 'users#conversation', via: 'get'

  match '/passwords/reset_sent' => 'static#reset_sent', via: 'get'

  devise_for :users, :controllers => { :passwords => "passwords", :sessions => 'users/sessions', :registrations => 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    get :autocomplete_epithet_name, :on => :collection
  end

  root 'static#landing'

  get "/donate" => 'static#donate'
  get "/sign-up-raffle" => 'static#signupraffle'
  get "/about" => 'static#about'
  get "/igg" => 'static#igg'
  get "/thankyou" => 'static#thankyou'
  get "api" => 'static#api'

  devise_scope :user do
    match '/users/sign_up' => 'users/registrations#create', via: 'post'
  end

end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  postal     :string
#  created_at :datetime
#  updated_at :datetime
#

class Newsletter < ActiveRecord::Base

	validates :email, uniqueness: true, :presence => true
	validates :postal, :presence => true


end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    else
      @newsletters = Newsletter.all
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    end
  end

  # GET /newsletters/new
  def new
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    else
      @newsletter = Newsletter.new
    end
  end

  # GET /newsletters/1/edit
  def edit
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    end
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        flash[:notice] = 1
        format.html { redirect_to root_url, notice: "You have been successfully registered" }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { redirect_to root_url, notice: ("#{@newsletter.errors.full_messages[0]}" || "") }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    else
      respond_to do |format|
        if @newsletter.update(newsletter_params)
          format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
          format.json { render :show, status: :ok, location: @newsletter }
        else
          format.html { render :edit }
          format.json { render json: @newsletter.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    unless user_signed_in? and current_user.permissions != 0 
      redirect_to "/no_access"
      return
    else
      @newsletter.destroy
      respond_to do |format|
        format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:name, :email, :postal)
    end
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :postal %><br>
    <%= f.text_field :postal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<div class="container">
  <h1>Listing Newsletter Registrations</h1>

  <table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Postal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.name %></td>
        <td><%= newsletter.email %></td>
        <td><%= newsletter.postal %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>
</div>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newsletter.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @newsletter.postal %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>