config/routes.rb
Rails.application.routes.draw do

  resources :conversations_users
  resources :conversations
  resources :geocoded_addresses
  resources :distances
  resources :request_accesses
  resources :flags
  resources :ratings

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get 'search/new_search'
  get 'search/index'
  get 'search/classic'

  match "/classic_driver", to: 'search#classic_driver', via: 'get'
  match "/people_data", to: 'search#people_data', via: 'get'
  match "/accessibility", to: 'static#accessibility', via: 'get'

  match "/newConversation/:other_participant_id", to: 'conversations#create', via: 'get'

  match '/people', to: 'search#people', via: 'get'
  match '/search', to: 'search#classic', via: 'get'
  match '/browse', to: 'search#new_search', via: 'get'

  resources :saveds
  resources :user_uploads
  resources :resource_uploads
  resources :resources_tags
  resources :newsletters

  match 'submit_resource', to: 'static#submit_resource', via: 'post'
  match '/resources/new', to: 'resources#new', via: 'get'
  match '/resources/clarifyContent', to: 'resources#clarifyContent', via: 'get'
  match '/resources/:id', to: 'resources#rerouter', via: 'get'

  resources :resources do
    get :autocomplete_tag_name, :on => :collection
  end

  match '/r/:id/:resource_name', to: 'resources#show', via: 'get'
  resources :resources
  match '/resources/:id/categories', to: 'resources#categories', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#weblinks', via: 'get'
  match '/resources/:id/photo', to: 'resources#photo', via: 'get'
  match '/resources/:id/success', to: 'resources#success', via: 'get'
  match '/resource_uploads/:id/crop', to: 'resource_uploads#crop', via: 'get'
  match '/user_uploads/:id/crop', to: 'user_uploads#crop', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#update_weblinks', via: 'post'

  match '/resources_tags/:resource_id/:tag_id/create', to: 'resources_tags#custom_create', via: 'post'
  match '/resources_tags/:resource_id/:tag_id/destroy', to: 'resources_tags#custom_destroy', via: 'post'

  match '/saved/:resource_id/:user_id/create', to: 'saveds#custom_create', via: 'post'
  match '/saved/:resource_id/:user_id/destroy', to: 'saveds#custom_destroy', via: 'post'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/users/:id/conversations' => 'users#conversations', via: 'get'
  match '/users/:id/conversations/:conversation_id' => 'users#conversation', via: 'get'

  match '/passwords/reset_sent' => 'static#reset_sent', via: 'get'

  devise_for :users, :controllers => { :passwords => "passwords", :sessions => 'users/sessions', :registrations => 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    get :autocomplete_epithet_name, :on => :collection
  end

  root 'static#landing'

  get "/donate" => 'static#donate'
  get "/sign-up-raffle" => 'static#signupraffle'
  get "/about" => 'static#about'
  get "/igg" => 'static#igg'
  get "/thankyou" => 'static#thankyou'
  get "api" => 'static#api'

  devise_scope :user do
    match '/users/sign_up' => 'users/registrations#create', via: 'post'
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id             :integer          not null, primary key
#  name           :string
#  taggings_count :integer          default(0)
#

class Tag < ActiveRecord::Base
	has_many :resources_tags
  has_many :resources, through: :resources_tags
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :life_situation %><br>
    <%= f.check_box :life_situation %>
  </div>
  <div class="field">
    <%= f.label :nonprofit_services %><br>
    <%= f.check_box :nonprofit_services %>
  </div>
  <div class="field">
    <%= f.label :one_time %><br>
    <%= f.check_box :one_time %>
  </div>
  <div class="field">
    <%= f.label :jobs %><br>
    <%= f.check_box :jobs %>
  </div>
  <div class="field">
    <%= f.label :housing %><br>
    <%= f.check_box :housing %>
  </div>
  <div class="field">
    <%= f.label :forprofit_services %><br>
    <%= f.check_box :forprofit_services %>
  </div>
  <div class="field">
    <%= f.label :marketplace %><br>
    <%= f.check_box :marketplace %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="container">
	<h1>Editing tag</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @tag %> |
	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/index.html.erb
<div class="container">
  <h1>Listing tags</h1>

 <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Count</th>
        <th>Life situation</th>
        <th>Nonprofit services</th>
        <th>One time</th>
        <th>Jobs</th>
        <th>Housing</th>
        <th>Forprofit services</th>
        <th>Marketplace</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><%= tag.count %></td>
          <td><%= tag.life_situation %></td>
          <td><%= tag.nonprofit_services %></td>
          <td><%= tag.one_time %></td>
          <td><%= tag.jobs %></td>
          <td><%= tag.housing %></td>
          <td><%= tag.forprofit_services %></td>
          <td><%= tag.marketplace %></td>
          <td><%= link_to 'Show', tag %></td>
          <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
          <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<div class="container">
	<h1>New tag</h1>

	<%= render 'form' %>

	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @tag.name %>
  </p>

  <p>
    <strong>Count:</strong>
    <%= @tag.count %>
  </p>

  <p>
    <strong>Life situation:</strong>
    <%= @tag.life_situation %>
  </p>

  <p>
    <strong>Nonprofit services:</strong>
    <%= @tag.nonprofit_services %>
  </p>

  <p>
    <strong>One time:</strong>
    <%= @tag.one_time %>
  </p>

  <p>
    <strong>Jobs:</strong>
    <%= @tag.jobs %>
  </p>

  <p>
    <strong>Housing:</strong>
    <%= @tag.housing %>
  </p>

  <p>
    <strong>Forprofit services:</strong>
    <%= @tag.forprofit_services %>
  </p>

  <p>
    <strong>Marketplace:</strong>
    <%= @tag.marketplace %>
  </p>

  <%= link_to 'Edit', edit_tag_path(@tag) %> |
  <%= link_to 'Back', tags_path %>
</div>