config/routes.rb
Rails.application.routes.draw do

  resources :conversations_users
  resources :conversations
  resources :geocoded_addresses
  resources :distances
  resources :request_accesses
  resources :flags
  resources :ratings

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get 'search/new_search'
  get 'search/index'
  get 'search/classic'

  match "/classic_driver", to: 'search#classic_driver', via: 'get'
  match "/people_data", to: 'search#people_data', via: 'get'
  match "/accessibility", to: 'static#accessibility', via: 'get'

  match "/newConversation/:other_participant_id", to: 'conversations#create', via: 'get'

  match '/people', to: 'search#people', via: 'get'
  match '/search', to: 'search#classic', via: 'get'
  match '/browse', to: 'search#new_search', via: 'get'

  resources :saveds
  resources :user_uploads
  resources :resource_uploads
  resources :resources_tags
  resources :newsletters

  match 'submit_resource', to: 'static#submit_resource', via: 'post'
  match '/resources/new', to: 'resources#new', via: 'get'
  match '/resources/clarifyContent', to: 'resources#clarifyContent', via: 'get'
  match '/resources/:id', to: 'resources#rerouter', via: 'get'

  resources :resources do
    get :autocomplete_tag_name, :on => :collection
  end

  match '/r/:id/:resource_name', to: 'resources#show', via: 'get'
  resources :resources
  match '/resources/:id/categories', to: 'resources#categories', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#weblinks', via: 'get'
  match '/resources/:id/photo', to: 'resources#photo', via: 'get'
  match '/resources/:id/success', to: 'resources#success', via: 'get'
  match '/resource_uploads/:id/crop', to: 'resource_uploads#crop', via: 'get'
  match '/user_uploads/:id/crop', to: 'user_uploads#crop', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#update_weblinks', via: 'post'

  match '/resources_tags/:resource_id/:tag_id/create', to: 'resources_tags#custom_create', via: 'post'
  match '/resources_tags/:resource_id/:tag_id/destroy', to: 'resources_tags#custom_destroy', via: 'post'

  match '/saved/:resource_id/:user_id/create', to: 'saveds#custom_create', via: 'post'
  match '/saved/:resource_id/:user_id/destroy', to: 'saveds#custom_destroy', via: 'post'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/users/:id/conversations' => 'users#conversations', via: 'get'
  match '/users/:id/conversations/:conversation_id' => 'users#conversation', via: 'get'

  match '/passwords/reset_sent' => 'static#reset_sent', via: 'get'

  devise_for :users, :controllers => { :passwords => "passwords", :sessions => 'users/sessions', :registrations => 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    get :autocomplete_epithet_name, :on => :collection
  end

  root 'static#landing'

  get "/donate" => 'static#donate'
  get "/sign-up-raffle" => 'static#signupraffle'
  get "/about" => 'static#about'
  get "/igg" => 'static#igg'
  get "/thankyou" => 'static#thankyou'
  get "api" => 'static#api'

  devise_scope :user do
    match '/users/sign_up' => 'users/registrations#create', via: 'post'
  end

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h5><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h5>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% unless @resource.user_id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>

  <%= f.hidden_field :basics_complete, :value => true %>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :name, "RESOURCE NAME" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, :placeholder => " e.g. Empire Association of the Deaf", :class => "form-control", :maxlength => "63" %>
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :address_street, "ADDRESS" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :address_street, :placeholder => "Street Number and Street Name", :class => "form-control" %>
    </div>
    <div class="col-sm-4">

    </div>
    <div class="col-sm-8">
      <%= f.text_field :address_city, :placeholder => "City", :class => "form-control", :style => "margin-top: 4px;" %>
    </div>
    <div class="col-sm-4">

    </div>
    <div class="col-sm-5">
      <%= f.select(:address_state, us_states, {include_blank: false}, {class: "form-control inline-input", style: "margin-top: 4px;"}) %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :address_postal, :placeholder => "Postal code", :class => "form-control inline-input", :style => "margin-top: 4px;" %>
    </div>
  </div>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :nationwide, "NATIONWIDE" %>
      <button type="button" style="border: 0px solid transparent; font-size: 11px;" class="btn btn-default btn-sm popover-dismiss" data-toggle="popover" title="Nationwide Resources" data-content="Though most resources on Ability List are discovered through geographical searches, resources like hotlines and some websites sometimes do not have a physical location. We call these nationwide resources.">?</button>
    </div>
    <div class="col-sm-8">
      <%= f.check_box :nationwide %> Yes, this resource provides for all regions of the nation
      <style>
.popover-title {
    font-weight: bold;
    font-size: 15px;
}
.popover-content {
    font-size: 12px;
    width: 240px;
}
      </style>
      <script>


    $('.popover-dismiss')
       .popover()
       .click(function(e) { 
           e.preventDefault(); 
           $(this).focus(); 
       });
      </script>
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :anonymous, "ANONYMOUS" %>
    </div>
    <div class="col-sm-8">
      <%= f.check_box :anonymous %> I don't want my name displayed next to this resource
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :phone, "PHONE NUMBER" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :phone, :class => "form-control", :placeholder => " 999-999-9999" %>
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :description, "DESCRIPTION" %>
    </div>
    <div class="col-sm-8" style="text-align: right;">
      <%= f.bootsy_area :description  %>
    </div>
  </div>

  <div class="actions flow-submit-container">
    <%= button_to "Save & Continue", {}, {class: 'btn btn-info'} %>
  </div>
<% end %>

app/views/resources/_photo_form.html.erb
<%= form_for(@resource_upload) do |f| %>
  <% if @resource_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_upload.errors.count, "error") %> prohibited this resource_upload from being saved:</h2>

      <ul>
      <% @resource_upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :resource_id, :value => params[:id] %>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :photo, "RESOURCE PHOTO" %>
      <div style="font-size: 11px;">(Optional.)</div>
    </div>
    <div class="col-sm-8">
      <%= f.file_field :photo %><br>
      <%= button_to "Upload File", {}, {class: 'btn btn-primary'} %>
<% end %>
    </div>
  </div>

<!-- THERE IS A SEPARATE FORM FOR CROPPING -->
<% if @resource.resource_upload %>
    <div class="row form-row form-row-border-bottom">
      <div class="col-sm-4">
        <label for="resource_upload_photo">PREVIEW</label>
      </div>
      <div class="col-sm-8">
         <div class="resource-photo-inside" style="width: 160px;">
            <%= image_tag @resource.resource_upload.photo.url(:medium), :class => "fitted-image" %>
          </div>
          <% if @resource.resource_upload %>
          
            <a class="btn btn-default" style="margin-top: 20px;" href="/resource_uploads/<%= @resource.resource_upload.id %>/crop" rel="nofollow">Crop Tool</a>
            <a data-confirm="Are you sure? This cannot be undone." class="btn btn-default" style="margin-top: 20px;" data-method="delete" href="/resource_uploads/<%= @resource_upload.id %>" rel="nofollow">Delete Image</a>
          <% end %>
      </div>
    </div>
<% end %>

  <div class="flow-submit-container">
    <a type="button" style="margin-left: 20px;" href="/resources/<%=@resource.id%>/success" class="btn btn-info">Save & Publish</a>
  </div>

app/views/resources/_weblinks_form.html.erb
<%= form_for @resource, url: '/resources/' + @resource.id.to_s + '/weblinks', :method => :POST, html: {} do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h5><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h5>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :website, "WEBSITE ADDRESS" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :website, :placeholder => " e.g. http://www.empireassociation.com", :class => "form-control" %>
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :email, "CONTACT EMAIL" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :email, :placeholder => " e.g. admin@resource.org", :class => "form-control" %>
    </div>
  </div>

  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :facebook, "SOCIAL MEDIA LINKS" %>
    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :facebook, :placeholder => " Facebook", :class => "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">

    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :twitter, :placeholder => " Twitter", :class => "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :linkedin, :placeholder => " Linkedin", :class => "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">

    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :yelp, :placeholder => " Yelp", :class => "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :googleplus, :placeholder => " Google Plus", :class => "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">

    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.text_field :foursquare, :placeholder => " Foursquare", :class => "form-control" %>
      </div>
    </div>
  </div>


  <div class="actions flow-submit-container">
    <%= button_to "Save & Continue", {}, {class: 'btn btn-info'} %>
  </div>
<% end %>

app/views/resources/categories.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 1} %>
<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Next, type comma separated tags that describe this resource.</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">These tags help people narrow down their searches to exactly what they’re looking for. </h4>
</div>

<div class="container resource-form-container">

<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h5><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h5>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <label>COMMON TAGS</label>
    </div>
    <div class="col-sm-8">
<a href="#" onclick="javascript: appendTagList('housing', this)" class="blue-link">housing<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('education', this)" class="blue-link">education<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('transportation', this)" class="blue-link">transportation<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('jobs', this)" class="blue-link">jobs<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('recreation', this)" class="blue-link">recreation<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('medical resources', this)" class="blue-link">medical resources<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('assistance', this)" class="blue-link">assistance<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('organizations', this)" class="blue-link">organizations<span style='color: #999;'>,</span></a>
<a href="#" onclick="javascript: appendTagList('events', this)" class="blue-link">events<span style='color: #999;'>,</span></a>

    </div>
  </div>
  <div class="row form-row form-row-border-bottom">
    <div class="col-sm-4">
      <%= f.label :tag_list, "TYPE YOUR OWN TAGS" %>
    </div>
    <div class="col-sm-8">
      <%= f.hidden_field :route_to, :value => "weblinks" %>
      <%= f.autocomplete_field :tag_list, autocomplete_tag_name_resources_path, :"data-delimiter" => ', ', :value => @resource.tags.join(", "), :class => "form-control", :placeholder => "transportation, limited mobility" %> 
    </div>
  </div>


	<div class="flow-submit-container">
		<%= f.submit 'Save & Continue', :class => 'btn btn-info' %>
		<% end %>

	</div>
</div>

<script>
/* this disables form submission on enter key -- because it looks as if you might be able to select existing tags using enter, when you really can't */
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
/* this hides the 'no existing matches' response when the tag doesn't exist */
$(resource_tag_list).on('autocompleteresponse', function(event, ui) {
      var content;
      if (((content = ui.content) != null ? content[0].id.length : void 0) === 0) {
        $(this).autocomplete('close');
      }
  });
function appendTagList(string, ele) {
  var target = document.getElementById("resource_tag_list");
  if (target.value.length > 0 && target.value.substr(target.value.length - 1) != ",") {
    target.value += ",";
  }
  target.value += " " + string;
  ele.style.display = 'none';
}
</script>

app/views/resources/clarifyContent.html.erb
<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Choose what you'd like to share.</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">This is to make sure the content you're
		sharing gets saved to the right place.</h4>
</div>

<div class="container resource-form-container">
	<div class="row" style="margin-left: 8px; margin-right: 8px;">
		<div class="col-sm-6 content-clarify-btn content-clarify-btn-active" id="my-story-btn" onclick="toggleSelectedSharingContent('my-story-btn')">
			<h4><i class="fa fa-user fa-lg"></i> &nbsp;My story</h4>
			This is about me, my interests and things I'm looking for. I'm open to connecting with others about what I share.
		</div>
		<div class="col-sm-6 content-clarify-btn" id="community-resource-btn" onclick="toggleSelectedSharingContent('community-resource-btn')">
			<h4><i class="fa fa-map-signs fa-lg"></i> &nbsp;A community resource</h4>

			This is an organization, event or other public information that others may find interesting or useful.

		</div>
	</div>
	<div class="row">
		<div class="col-sm-12" style="margin-top: 40px; border-top: 1px solid #eee; text-align: center;">
			<a id='confirm-continue-btn' href="<%= edit_user_path(current_user)%>" class="btn btn-info" type="submit" style=" margin-top: 15px;">Confirm &amp; Continue</a>
	  </div>
	</div>
</div>
<script>
	var toggleSelectedSharingContent = function(id) {
		var otherButton = {
			'my-story-btn': 'community-resource-btn',
			'community-resource-btn': 'my-story-btn'
		};
		var targetOfButton = {
			'my-story-btn': '<%= edit_user_path(current_user)%>',
			'community-resource-btn': '/resources/new'
		};
		var thisButton = $('#' + id);
		if(thisButton.hasClass('content-clarify-btn-active')) {
			// remove the class
			thisButton.removeClass('content-clarify-btn-active');
			// add it to the other button
			$('#' + otherButton[id]).addClass('content-clarify-btn-active');
			// update target of confirm button
			$('#confirm-continue-btn').attr('href', targetOfButton[id]);
		} else {
			// remove the class from the other button
			$('#' + otherButton[id]).removeClass('content-clarify-btn-active');
			// add it to this button
			thisButton.addClass('content-clarify-btn-active');
			// update target of confirm button
			$('#confirm-continue-btn').attr('href', targetOfButton[id]);
		}
	};
</script>

app/views/resources/edit.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 0} %>

<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Let's start with the basics.</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">Be sure to provide the full address or postal code so users can find this resource by it’s location.</h4>
</div>

<div class="container resource-form-container">
	<%= render 'form' %>
</div>

app/views/resources/index.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.css
">
<style>
body { font-size: 140%; }
#resources-table_filter {
  padding-right: 50px;
}
</style>

<div class="container">
  <h1>Listing Resources</h1>


  <table class="table table-striped table-bordered" id="resources-table", data-source="<%= resources_path(format: :json) %>">
    <thead>
      <tr>
        <th>Photo</th>
        <th>Id</th>
        <th>Name</th>
        <th>User</th>
        <th>Nationwide</th>
        <th>Views</th>
        <th>State</th>
        <th>Postal</th>
        <th></th>

      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>


</div>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js
"></script>

<script>
jQuery(document).ready(function() {
  $('#resources-table').dataTable({
    "processing": true,
    "serverSide": true,
    "order": [[0, 'desc']],
    "ajax": $('#resources-table').data('source'),
    "pagingType": "full_numbers",
    // optional, if you want full pagination controls.
    // Check dataTables documentation to learn more about
    // available options.
  });
});
</script>

app/views/resources/new.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 0} %>

<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Let's start with the basics.</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">Be sure to provide the full address or postal code so users can find this resource by it’s location.</h4>
</div>

<div class="container resource-form-container">
	<%= render 'form' %>
</div>

app/views/resources/photo.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 3} %>

<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Last step!</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">It’s important to provide a high quality image like a logo or icon that represents this resource. <!--Be sure to use the photo crop tool to fit the image in place just right. --></h4>
</div>

<div class="container resource-form-container">
	<%= render 'photo_form' %>
</div>

app/views/resources/photo_edit.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 3} %>

<div class="container">
	<h2 style="font-weight: 300; text-align: center;">Last step!</h2>
	<h4 style="font-weight: 300; text-align: center; color: #999;">It’s important to provide a high quality image like a logo or icon that represents this resource. Be sure to use the photo crop tool to fit the image in place just right.</h4>
</div>

<div class="container resource-form-container">
	<%= render 'photo_form' %>
	<div class="flow-submit-container">
	  <a type="button" href="/resources/<%=@resource.id%>" class="btn btn-info">Save & Return</a>
	</div>
</div>

app/views/resources/show.html.erb
<div class="resource-head-color">
  <div class="container">
    <% if @resource.name.length < 50 %>
    <h3 class="resource-title">
    <% else %>
    <h4 class="resource-title">
    <% end %>
      <%= @resource.name %>

      <% if @resource.nationwide == 1 %>
        <span style="font-size: 11px; cursor:pointer;" class="label label-default">Nationwide</span>
      <% end %>

      <% if user_signed_in? %>
        <div class="btn-group pull-right">
          <button id="btnGroupVerticalDrop2" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Options
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop2">
            <% if current_user.can_edit_resource(@resource.user_id) %>
              <li><a href="/resources/<%= @resource.id%>/edit">Edit</a></li>
              <li><a data-confirm="Are you sure? This cannot be undone." data-method="delete" href="/resources/<%= @resource.id %>" rel="nofollow">Delete</a></li>
            <% else %>
              <li><a data-toggle="modal" data-target="#flagModal" style="cursor: pointer;">Flag</a></li>
              <li><a data-toggle="modal" data-target="#accessModal" style="cursor: pointer;">Request Access</a></li>              
            <% end %>
          </ul>
        </div>
      <% end %>
    <% if @resource.name.length < 50 %>
    </h3>
    <% else %>
    </h4>
    <% end %>
    <div class="resource-rating-comments-title">
      <%= render 'resources/partials/profile/rating_count' %>
    </div>
  </div>
</div>
<div class="container profile-border-bottom">
  <div class="row">
    <div class="col-sm-2">
      <div class="resource-photo-container">
        <% if @resource.resource_upload %>
          <div class="resource-photo-inside">
            <%= image_tag @resource.resource_upload.photo.url(:medium), :class => "fitted-image-resource" %>
          </div>
        <% else %>
          <div class="profile-photo-inside-resource">
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-10 resource-actions-container">
      <%= render 'resources/partials/profile/actions' %>
    </div>
  </div>
</div>

<%= render 'resources/partials/profile/share_modal' %>

<% if user_signed_in? %>

<%= render 'resources/partials/profile/rating_modal' %>
<%= render 'resources/partials/profile/flag_modal' %>
<%= render 'resources/partials/profile/access_modal' %>

<script>
function save_resource() {
  var create_url = "/saved/" + "<%= @resource.id%>/<%= current_user.id%>" + "/create";
  $.ajax({
    url: create_url,
    type: 'POST',
    context: document.body
  }).done(function() {
    document.getElementById("save-toggle").innerHTML = "<i class='fa fa-heart' style='color: rgba(220,20,60, 0.6);'></i> &nbsp; SAVED";
    $("#save-toggle").attr('onclick', 'unsave_resource();');
  });
}
function unsave_resource() {
    var destroy_url = "/saved/" + "<%= @resource.id%>/<%= current_user.id%>"  + "/destroy";
    $.ajax({
      url: destroy_url,
      type: 'POST',
      context: document.body
    }).done(function() {
      document.getElementById("save-toggle").innerHTML = "<i class='fa fa-heart'></i> &nbsp; SAVE";
      $("#save-toggle").attr('onclick', 'save_resource();');      
    });
}
</script>
<% else %>
<script>
  $('#save-toggle').tooltip();
  $('#rate-btn').tooltip();
</script>
<% end %>

<div class="container">
  <div class="row">
    <%= render 'resources/partials/profile/description' %>    
    <%= render 'resources/partials/profile/details' %>
  </div>
</div>

app/views/resources/success.html.erb
<div class="container">
	<div class="big-success-check-container">
		<i style="color: #47A447;" class="fa fa-check-circle-o fa-6 big-success-check"></i>
	</div>

	<div class="row">
	  <div class="col-md-8 col-md-offset-2 form-row-border-bottom">
			<h2 style="font-weight: 300; text-align: center;">Your submission was successful.</h2>
			<h4 style="font-weight: 300; text-align: center; color: #999;">Thank you for sharing what you know and contributing to our growing community!</h4> 
	  </div>
	</div>




  <div class="flow-submit-container" style="margin-top: 20px;">
    <a type="button" href="/resources/<%=@resource.id%>" class="btn btn-info">VIEW RESOURCE</a>
    <a type="button" href="/resources/new" style="margin-left: 30px;" class="btn btn-success">SUBMIT ANOTHER</a>
  </div>
</div>

app/views/resources/weblinks.html.erb
<%= render partial: "partials/new_resource_breadcrumb", locals: {active: 2} %>

<div class="container">
	<h4 style="font-weight: 300; text-align: center; color: #999;">Here you can specify an existing website and provide links to popular social media accounts.</h4>
</div>

<div class="container resource-form-container">
	<%= render 'weblinks_form' %>
</div>