config/routes.rb
Rails.application.routes.draw do

  resources :conversations_users
  resources :conversations
  resources :geocoded_addresses
  resources :distances
  resources :request_accesses
  resources :flags
  resources :ratings

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get 'search/new_search'
  get 'search/index'
  get 'search/classic'

  match "/classic_driver", to: 'search#classic_driver', via: 'get'
  match "/people_data", to: 'search#people_data', via: 'get'
  match "/accessibility", to: 'static#accessibility', via: 'get'

  match "/newConversation/:other_participant_id", to: 'conversations#create', via: 'get'

  match '/people', to: 'search#people', via: 'get'
  match '/search', to: 'search#classic', via: 'get'
  match '/browse', to: 'search#new_search', via: 'get'

  resources :saveds
  resources :user_uploads
  resources :resource_uploads
  resources :resources_tags
  resources :newsletters

  match 'submit_resource', to: 'static#submit_resource', via: 'post'
  match '/resources/new', to: 'resources#new', via: 'get'
  match '/resources/clarifyContent', to: 'resources#clarifyContent', via: 'get'
  match '/resources/:id', to: 'resources#rerouter', via: 'get'

  resources :resources do
    get :autocomplete_tag_name, :on => :collection
  end

  match '/r/:id/:resource_name', to: 'resources#show', via: 'get'
  resources :resources
  match '/resources/:id/categories', to: 'resources#categories', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#weblinks', via: 'get'
  match '/resources/:id/photo', to: 'resources#photo', via: 'get'
  match '/resources/:id/success', to: 'resources#success', via: 'get'
  match '/resource_uploads/:id/crop', to: 'resource_uploads#crop', via: 'get'
  match '/user_uploads/:id/crop', to: 'user_uploads#crop', via: 'get'
  match '/resources/:id/weblinks', to: 'resources#update_weblinks', via: 'post'

  match '/resources_tags/:resource_id/:tag_id/create', to: 'resources_tags#custom_create', via: 'post'
  match '/resources_tags/:resource_id/:tag_id/destroy', to: 'resources_tags#custom_destroy', via: 'post'

  match '/saved/:resource_id/:user_id/create', to: 'saveds#custom_create', via: 'post'
  match '/saved/:resource_id/:user_id/destroy', to: 'saveds#custom_destroy', via: 'post'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/users/:id/conversations' => 'users#conversations', via: 'get'
  match '/users/:id/conversations/:conversation_id' => 'users#conversation', via: 'get'

  match '/passwords/reset_sent' => 'static#reset_sent', via: 'get'

  devise_for :users, :controllers => { :passwords => "passwords", :sessions => 'users/sessions', :registrations => 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    get :autocomplete_epithet_name, :on => :collection
  end

  root 'static#landing'

  get "/donate" => 'static#donate'
  get "/sign-up-raffle" => 'static#signupraffle'
  get "/about" => 'static#about'
  get "/igg" => 'static#igg'
  get "/thankyou" => 'static#thankyou'
  get "api" => 'static#api'

  devise_scope :user do
    match '/users/sign_up' => 'users/registrations#create', via: 'post'
  end

end

app/models/distance.rb
# == Schema Information
#
# Table name: distances
#
#  id           :integer          not null, primary key
#  location     :string
#  resource_id  :integer
#  distance     :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  cache_string :string
#

class Distance < ActiveRecord::Base
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  before_action :set_distance, only: [:show, :edit, :update, :destroy]

  # GET /distances
  # GET /distances.json
  def index
    @distances = Distance.all
  end

  # GET /distances/1
  # GET /distances/1.json
  def show
  end

  # GET /distances/new
  def new
    @distance = Distance.new
  end

  # GET /distances/1/edit
  def edit
  end

  # POST /distances
  # POST /distances.json
  def create
    @distance = Distance.new(distance_params)

    respond_to do |format|
      if @distance.save
        format.html { redirect_to @distance, notice: 'Distance was successfully created.' }
        format.json { render :show, status: :created, location: @distance }
      else
        format.html { render :new }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distances/1
  # PATCH/PUT /distances/1.json
  def update
    respond_to do |format|
      if @distance.update(distance_params)
        format.html { redirect_to @distance, notice: 'Distance was successfully updated.' }
        format.json { render :show, status: :ok, location: @distance }
      else
        format.html { render :edit }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distances/1
  # DELETE /distances/1.json
  def destroy
    @distance.destroy
    respond_to do |format|
      format.html { redirect_to distances_url, notice: 'Distance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distance
      @distance = Distance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distance_params
      params.require(:distance).permit(:location, :resource_id, :distance, :cache_string)
    end
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/views/distances/_form.html.erb
<%= form_for(@distance) do |f| %>
  <% if @distance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distance.errors.count, "error") %> prohibited this distance from being saved:</h2>

      <ul>
      <% @distance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :resource_id %><br>
    <%= f.number_field :resource_id %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/distances/edit.html.erb
<h1>Editing Distance</h1>

<%= render 'form' %>

<%= link_to 'Show', @distance %> |
<%= link_to 'Back', distances_path %>

app/views/distances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Distances</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Location</th>
      <th>Resource</th>
      <th>Distance</th>
      <th>Cache string</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distances.each do |distance| %>
      <tr>
        <td><%= distance.id %></td>
        <td><%= distance.location %></td>
        <td><%= distance.resource_id %></td>
        <td><%= distance.distance %></td>
        <td><%= distance.cache_string %></td>
        <td><%= link_to 'Show', distance %></td>
        <td><%= link_to 'Edit', edit_distance_path(distance) %></td>
        <td><%= link_to 'Destroy', distance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distance', new_distance_path %>

app/views/distances/new.html.erb
<h1>New Distance</h1>

<%= render 'form' %>

<%= link_to 'Back', distances_path %>

app/views/distances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @distance.location %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @distance.resource_id %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @distance.distance %>
</p>

<%= link_to 'Edit', edit_distance_path(@distance) %> |
<%= link_to 'Back', distances_path %>